name: MorphPlayers
author: PalkiaDude
version: "1.0.0"
api: [1.13.0]
description: Morph into mobs.
main: PalkiaDude\MorphPlayers\Main

commands:
    morphcreeper:
        description: "Morph into a creeper!"
